### ISSUE TITLE
mmat-1.0.jar中没有主清单属性

### ISSUE THREAD

**Issue by zhj0128** [hehonghui/mmat#1]
使用jar包时，命令行提示 mmat-1.0.jar中没有主清单属性，通过解压后在MANIFEST.MF中只看到Manifest-Version: 1.0，没看到 ”Main-Class:” 的描述，想请教下，是不是我执行错了

**Comment by lilingquan** [comment]
用源代码重打包

**Comment by hehonghui** [comment]
> 使用jar包时，命令行提示 mmat-1.0.jar中没有主清单属性，通过解压后在MANIFEST.MF中只看到Manifest-Version: 1.0，没看到 ”Main-Class:” 的描述，想请教下，是不是我执行错了

抱歉，之前打包有点问题。已经更新jar文件
