### ISSUE TITLE
测试出来的结果量很少

### ISSUE THREAD

**Issue by mikaelzero** [hehonghui/mmat#5]
不知道是自己使用姿势有问题还是怎么的，报告显示泄漏就两条，我感觉应该不对，图片部分的错误是  Can't read bitmap data in java heap on Android 8.0 and above!

下面是使用

通过 gradle plugin 使用MMAT,然后运行app，自己手动点击页面，使app回到后台，执行命令./gradlew startMmatRunner

我查看的话主要就是查看html文件

**Comment by innovatorCL** [comment]
我运行了也是如此，图片部分的错误是 Can't read bitmap data in java heap on Android 8.0 and above!

**Comment by hehonghui** [comment]
这是正常的提示， Android 8.0之后图片的数据已经不存储在 java 堆了。

innovatorCL ***@***.***> 于2021年7月16日周五 下午1:06写道：

**Comment by innovatorCL** [comment]
是的，Android 4.0—7.X 的 Bitmap 内存分配是在 Java Heap 分配的，8.0 及以上是在 Native Heap 分配的，所以 Android 8.0 以上用这个工具检测不了 Bitmap 的内存分配。
